spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    username: rm553326
    password: 091003
    driver-class-name: oracle.jdbc.OracleDriver
    show-sql: true
    properties:
        hibernate.format_sql: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
